### ISSUE TITLE
Restrictive license

### ISSUE THREAD

**Issue by sinkingsugar** [naomijub/edn-rs#10]
Great work!
Would really love to use this but, with all due respect to GNU software, it's quite restrictive to include this crate in a BSD2/MIT project. Any possibility to see a more open license?

Cheers!

**Comment by naomijub** [comment]
Hi @sinkingsugar Sure, do you want to make a PR changing the LICENSE?

**Comment by naomijub** [comment]
Sorry for the late response, github did not notify me

**Comment by sinkingsugar** [comment]
No worries,
I can make a PR but what kind of license is ups to you :) 
I generally use "BSD 3-Clause License"

**Comment by naomijub** [comment]
I think `BSD 3-Clause License` seems good, as well as MIT.

**Comment by naomijub** [comment]
f680038e496f845e2aa37e58e556ae66be4d82d1

**Comment by Kryptos-FR** [comment]
hi @naomijub, I'd like to re-open this issue.

LGPL is not better than GPL as it is also very restrictive. It's not clear whether it can be included as a crate in an MIT project, since it ends up being compiled together with the project (static linking).

Also LGPL is largely untested in court (while GPL has been), so the exact scope of the license is unclear. But I'm not a lawyer.

Wouldn't `MIT` or `BSD` fit better as suggested earlier in the comments? It seems that most crates in the rust community adopt such licenses.

**Comment by naomijub** [comment]
Ok

**Comment by naomijub** [comment]
https://github.com/naomijub/edn-rs/commit/37da726bb3cb8a3e0ff584cb6029faac0d9224bd
