### ISSUE TITLE
Use `HashSet` for `Edn::Set` 

### ISSUE THREAD

**Issue by naomijub** [naomijub/edn-rs#3]
the `set!` macro is already implemented, however initial implementation uses `Vec<Edn>`. The ideia is to convert `Edn::Set` inner type `Set` from `Vec<Edn>` to `HashSet<Edn>`

**Comment by naomijub** [comment]
@otaviopace Help! You had a GREAT IDEA to solve this

**Comment by evaporei** [comment]
Pull Request made: https://github.com/naomijub/edn-rs/pull/17 🎉 

Also, I had to follow with a `BTreeSet` solution instead of `HashSet`, because of hashing issues with `Hash{Map, Set}`, which is no problem with `BTree{Map, Set}`.

Most of the ideas came from: [mentat/edn](https://github.com/mozilla/mentat/tree/master/edn) crate.
